/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_modularaudio_util_thread_GetThreadID */

#ifndef _Included_uk_co_modularaudio_util_thread_GetThreadID
#define _Included_uk_co_modularaudio_util_thread_GetThreadID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_modularaudio_util_thread_GetThreadID
 * Method:    get_tid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_co_modularaudio_util_thread_GetThreadID_get_1tid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
